dist: xenial

language: python

python:
  - 3.7
  - 3.6
  - 3.5

before_install:
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb

install:
  - pip install tox tox-travis

script:
  - tox

after_script:
  - pip install codecov
  - codecov

notifications:
  email: false
